version: '1.8'

services:
  proxy:
    container_name: proxy
    image: nginx
    depends_on:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - ./proxy/cert:/etc/certs
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    container_name: atlanta-domains
    image: atlanta-domains
    build: 
      context: .
    environment:
      - NEXT_PUBLIC_APP_ENV=prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:3000
  frontend-sepolia:
    container_name: atlanta-domains-sepolia
    image: atlanta-domains
    build:
      context: .
    depends_on:
      - frontend
    environment:
      - NEXT_PUBLIC_APP_ENV=dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3001:3000