version: '1.8'

services:
  proxy:
    container_name: proxy
    image: nginx
    depends_on:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./templates:/etc/nginx/templates
      - ./cert:/etc/certs/frontend
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    container_name: atlanta-domains
    image: atlanta-domains
    build: 
      context: .
    ports:
      - 3000:3000